//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNARIZA
    {
        public int ISLEMID { get; set; }
        public Nullable<System.DateTime> GELISTARIH { get; set; }
        public string DURUM { get; set; }
        public Nullable<int> URUNSATIS { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual TBLURUNSATIS TBLURUNSATIS { get; set; }
    }
}
